global_args:

  n_all_samples: 200_000
  sample_date: "2024-09-05"

pipeline:

  - name: get_train_data

    args:
      visualize: True
      save_dags: True
      force_rerun: False

    stages:
    
      - HDFSCSVReadStage:
          name: label_data_read_stage
          args:
            path: "/projects/growth/test/analysis_tools/alg_label/coupon_planned_strategy/expose_label/single/${global_args.sample_date}"
            overwrite: False

      - CastStage:
          name: label_cast_stage
          after: 
            - label_data_read_stage
          inputs: 
            - label_data_read_stage.0
          args:
            col_name: label_value
            map:
              1: 0
              2: 0
              0: 1
              -1: -1
            recover_ori_col: True

      - CustomFunc:
          path: .
          module_name: filter_and_sample_label
          name: final_label_stage
          after: 
            - label_cast_stage
          inputs: 
            - label_cast_stage.0
          args:
            threshold: 0.5  # 示例阈值

      - HDFSORCReadStage:
          name: lucky_member_group_type_stage
          after: 
            - final_label_stage
          inputs: 
            - final_label_stage.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/order/order_message_part2/${global_args.sample_date}"
            select_cols: ["member_id", "lucky_member_group_type"]
            overwrite: False

      - MultiJoin:
          name: join_stage_1
          after: lucky_member_group_type_stage
          inputs:
            - final_label_stage.0
            - lucky_member_group_type_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: is_alt_member_stage
          after: 
            - join_stage_1
          inputs: 
            - join_stage_1.0
          args:
            path: "/projects/growth/prod/user-reach-label/view/label_view/${global_args.sample_date}"
            select_cols: ["member_id", "is_alt_member"]
            overwrite: False

      - MultiJoin:
          name: join_stage_2
          after: 
            - is_alt_member_stage
          inputs:
            - join_stage_1.0
            - is_alt_member_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: start_days_30d_stage
          after: 
            - join_stage_2
          inputs: 
            - join_stage_2.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/coupon-control/base/login_order_labels/${global_args.sample_date}"
            select_cols: ["member_id", "start_days_30d"]
            overwrite: False

      - MultiJoin:
          name: join_stage_3
          after: 
            - start_days_30d_stage
          inputs:
            - join_stage_2.0
            - start_days_30d_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: is_start_no_order_prefer_user_stage
          after: 
            - join_stage_3
          inputs: 
            - join_stage_3.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/coupon-control/base/login_order_labels/${global_args.sample_date}"
            select_cols: ["member_id", "is_start_no_order_prefer_user"]
            overwrite: False

      - MultiJoin:
          name: join_stage_4
          after: 
            - is_start_no_order_prefer_user_stage
          inputs:
            - join_stage_3.0
            - is_start_no_order_prefer_user_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: psm_360d_stage
          after: 
            - join_stage_4
          inputs: 
            - join_stage_4.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/coupon-control/base/member_income_psm_360d/${global_args.sample_date.replace('_', '-')}"
            select_cols: ["member_id", "psm_360d"]
            overwrite: False

      - MultiJoin:
          name: join_stage_5
          after: 
            - psm_360d_stage
          inputs:
            - join_stage_4.0
            - psm_360d_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: app_coupon_list_bw_days_30d_stage
          after: 
            - join_stage_5
          inputs: 
            - join_stage_5.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/coupon-control/base/coupon_bw_labels/${global_args.sample_date}"
            select_cols: ["member_id", "app_coupon_list_bw_days_30d"]
            overwrite: False

      - MultiJoin:
          name: join_stage_6
          after: 
            - app_coupon_list_bw_days_30d_stage
          inputs:
            - join_stage_5.0
            - app_coupon_list_bw_days_30d_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSORCReadStage:
          name: coupon_used_99_times_stage
          after: 
            - join_stage_6
          inputs: 
            - join_stage_6.0
          args:
            path: "/projects/growth/prod/user-reach-label/data/coupon-control/base/member_use_99_coupon_180d/${global_args.sample_date}"
            select_cols: ["member_id", "coupon_used_99_times", "all_coupon_used_times"]
            overwrite: False

      - MultiJoin:
          name: join_stage_7
          after: 
            - coupon_used_99_times_stage
          inputs:
            - join_stage_6.0
            - coupon_used_99_times_stage.0
          args:
            on: "member_id"
            how: "left"

      - HDFSCSVReadStage:
          name: active_user_churn_label_stage
          after: 
            - join_stage_7
          inputs: 
            - join_stage_7.0
          args:
            path: "/projects/growth/prod/wakeup_model/churn_prob/predict_result/${global_args.sample_date}/part-0.csv"
            select_cols: ["member_id", "active_user_churn_label"]
            overwrite: False

      - MultiJoin:
          name: join_stage_8
          after: 
            - active_user_churn_label_stage
          inputs:
            - join_stage_7.0
            - active_user_churn_label_stage.0
          args:
            on: "member_id"
            how: "left"

      - XGBImportance:
          name: xgb_feature_importance_stage
          after: 
            - join_stage_8
          inputs: 
            - join_stage_8.0
          args:
            label_col: "label_value"
            importance_type: "gain"

