# 使用 Ubuntu 作为基础镜像
FROM ubuntu:20.04

# 更换为清华大学的 Ubuntu 镜像源
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://ports.ubuntu.com/ubuntu-ports|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list

# 安装必要的工具、JDK 1.8、Python 3.10 和构建工具
RUN apt-get update && \
    apt-get install -y software-properties-common wget openjdk-8-jdk build-essential && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10 python3.10-venv python3.10-dev && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3.10 get-pip.py && \
    apt-get clean

# 安装 Hadoop
RUN wget -qO- https://mirrors.aliyun.com/apache/hadoop/core/hadoop-2.10.2/hadoop-2.10.2.tar.gz | tar -xz -C /usr/local/ && \
    mv /usr/local/hadoop-2.10.2 /usr/local/hadoop

# 设置 Hadoop 环境变量
ENV HADOOP_HOME=/usr/local/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin

# 安装 pydoop 2.0
RUN python3.10 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pydoop==2.0

# 设置工作目录
WORKDIR /app

ENV LANG C.UTF-8

# 复制依赖文件
COPY requirements.txt .

# 安装 Python 依赖
RUN python3.10 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-cache-dir -r requirements.txt

# 启动命令
CMD ["sh", "deploy_local.sh"]