# 使用 Ubuntu 作为基础镜像
FROM ubuntu:20.04

# 更换为清华大学的 Ubuntu 镜像源
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://ports.ubuntu.com/ubuntu-ports|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list

# 安装必要的工具、JDK 1.8、Python 3.10 和构建工具
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common wget openjdk-8-jdk build-essential tzdata && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y python3.10 python3.10-venv python3.10-dev && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3.10 get-pip.py && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 安装 Hadoop
RUN wget -qO- https://mirrors.aliyun.com/apache/hadoop/core/hadoop-2.10.2/hadoop-2.10.2.tar.gz | tar -xz -C /usr/local/ && \
    mv /usr/local/hadoop-2.10.2 /usr/local/hadoop

# 设置 Hadoop 环境变量
ENV HADOOP_HOME=/usr/local/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

# 下载并解压pydoop
WORKDIR /opt
RUN wget https://files.pythonhosted.org/packages/e9/d3/c96293ea3ee5b7f51ec742accfcf7fbe5a939d5e66c2d19c5dbdcea26d2b/pydoop-2.0.0.tar.gz \
    && tar xzf pydoop-2.0.0.tar.gz

# 安装pydoop
WORKDIR /opt/pydoop-2.0.0
RUN python3.10 setup.py install

# 设置工作目录
WORKDIR /app

ENV LANG C.UTF-8

# 复制依赖文件
COPY requirements.txt .

# 安装 Python 依赖
RUN python3.10 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-cache-dir -r requirements.txt

# 启动命令
ENV PYTHONPATH=/app
CMD ["python3.10", "web/server.py"]